#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#blog_list:
#    path: /blog
    # the controller value has the format 'controller_class::method_name'
#    controller: App\Controller\BlogController::list